CREATE TABLE customer (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(100),
    email       VARCHAR2(100),
    phone       VARCHAR2(15)
);

CREATE TABLE ticket (
    ticket_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  NUMBER REFERENCES customer(customer_id),
    issue_type   VARCHAR2(100),
    description  CLOB,
    status       VARCHAR2(20) DEFAULT 'Open',
    created_at   DATE DEFAULT SYSDATE
);
